config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get '/about', to: 'pages#about', as: :about
  resources :events, only: %i[index show]
  resources :athletes, only: %i[index show], param: :nickname
  resources :achievements, only: :index

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  authenticate :user, ->(user) { user.present? } do
    mount RailsPerformance::Engine => '/app_performance'
  end
end

app/models/achievement.rb
# frozen_string_literal: true

class Achievement < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/athlete.rb
# frozen_string_literal: true

class Athlete < ApplicationRecord
  has_many :results, dependent: :destroy

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_fill: [250, 250], preprocessed: true
    attachable.variant :web, resize_to_fill: [800, 800], preprocessed: true
  end

  validates :first_name, :last_name, presence: true
  validates :nickname, uniqueness: true, format: { with: /\A[a-z_-]{3,}\z/ }, presence: true
  validates :birth_date, presence: true, unless: :hide_birth_date

  scope :active, -> { where(exit_date: nil) }

  enum :gender, { male: 0, female: 1 }, validate: { allow_nil: false }

  def self.ransackable_attributes(_auth_object = nil)
    %w[exit_date]
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/command.rb
# frozen_string_literal: true

class Command < ApplicationRecord
  belongs_to :event, counter_cache: true
  has_many :results, dependent: :destroy

  validates :name, presence: true
  validates :position, numericality: { greater_than_or_equal_to: 1 }, presence: true
  validates :fractional_second, numericality: { only_integer: true, in: 0..99 }, allow_nil: true

  enum :kind, { plain: 0, tri: 1 }, default: 0, validate: { allow_nil: false }
  enum :category, { mf: 0, mm: 1, ff: 2 }, validate: { allow_nil: false }
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :commands, dependent: :destroy

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_fill: [200, 150], preprocessed: true
    attachable.variant :web, resize_to_fill: [1090, 774], preprocessed: true
  end

  validates :name, :date, presence: true

  scope :visible, -> { where(hidden: false) }
end

app/models/partner.rb
# frozen_string_literal: true

class Partner < ApplicationRecord
  has_one_attached :logo do |attachable|
    attachable.variant :thumb, resize_to_limit: [400, 200]
    attachable.variant :web, resize_to_limit: [600, 300]
  end

  validates :name, :link, presence: true
  validates :logo, attached: true
end

app/models/result.rb
# frozen_string_literal: true

class Result < ApplicationRecord
  belongs_to :athlete
  belongs_to :command, counter_cache: true

  validates :distance, numericality: { greater_than_or_equal_to: 0.1 }
  validates :stage, numericality: { greater_than_or_equal_to: 1 }, uniqueness: { scope: :command_id }
  validates :fractional_second, numericality: { only_integer: true, in: 0..99 }, allow_nil: true

  enum :kind, { run: 0, ski: 1, swim: 2, bike: 3 }, default: 0, validate: { allow_nil: false }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  validates :email, presence: true
end

app/controllers/achievements_controller.rb
# frozen_string_literal: true

class AchievementsController < ApplicationController
  def index
    @achievements = Achievement.order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/athletes_controller.rb
# frozen_string_literal: true

class AthletesController < ApplicationController
  def index
    @athletes = Athlete.active.order(:last_name).includes(image_attachment: :blob)
    @results_count = Command.joins(:results).group(:athlete_id).distinct(:command_id).count
  end

  def show
    @athlete = Athlete.find_by!(nickname: params[:nickname])
    render :show_ex if @athlete.exit_date

    @command_results =
      Command.joins(:results)
        .eager_load(:event)
        .where(results: { athlete_id: @athlete.id }, events: { hidden: false })
        .order(date: :desc)
        .distinct
    @positions_count = @command_results.where(position: 1..3).unscope(:order).group(:position).count
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events_grouped_by_year =
      Event.visible.includes(:commands).order(date: :desc).group_by { |event| event.date.year }
  end

  def show
    @event = Event.visible.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end

  def about
    @events_count = Event.count
    @commands_count = Command.count
    @position_counts = Command.where(position: 1..3).group(:position).count
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def head_info(tag, text)
    content_for :"meta_#{tag}", text
    text
  end

  def yield_head_info(tag, default_text = '')
    content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
  end

  def current_page?(page)
    case page
    when 'index'
      params[:controller] == 'pages' && params[:action] == 'index'
    when 'about'
      params[:controller] == 'pages' && params[:action] == 'about'
    else
      params[:controller] == page
    end
  end

  def human_result_time(time)
    return unless (total_time = time.total_time)

    time_format = '%M:%S'
    time_format = "%H:#{time_format}" if total_time.hour.positive?
    time_format = "#{time_format},#{format '%02d', time.fractional_second}" if time.fractional_second.present?

    result_time = total_time.strftime(time_format)
    result_time unless result_time == '00:00'
  end

  def human_result_pace(result)
    return unless result.total_time

    avg_sec = (time_to_sec(result.total_time) / result.distance.to_f).round
    return if avg_sec.zero?
    return format '%<min>d:%<sec>02d /км', min: avg_sec / 60, sec: avg_sec % 60 if result.run?
    return format '%<min>d:%<sec>02d /100м', min: avg_sec / 600, sec: avg_sec / 10 % 60 if result.swim?

    "#{(3600.0 / avg_sec).round(1)} км/ч"
  end

  def human_result_stage(result)
    result.command.plain? ? result.stage : human_result_kind(result)
  end

  def time_to_sec(time)
    (((time.hour * 60) + time.min) * 60) + time.sec
  end

  def human_command_category(event)
    t "activerecord.attributes.command.categories.#{event.category}"
  end

  def human_athlete_gender(athlete)
    t "activerecord.attributes.athlete.genders.#{athlete.gender}"
  end

  def human_result_kind(result)
    t "activerecord.attributes.result.kinds.#{result.kind}"
  end

  def human_distance(distance)
    return "#{(1000 * distance).to_i}м" if distance < 1

    "#{distance == distance.to_i ? distance.to_i : number_with_delimiter(distance)}км"
  end

  def sanitized_text(text)
    sanitize text, tags: %w[strong em s blockquote pre ol ul li a p], attributes: %w[href rel target]
  end

  def external_link_to(title = nil, options = nil, html_options = {}, &)
    link_to title, *[options, html_options.merge(target: '_blank', rel: 'noopener')].compact, &
  end

  def athlete_image_path(athlete, variant: :web)
    if athlete.image.attached?
      rails_representation_url athlete.image.variant(variant)
    else
      "/images/unknown_#{athlete.gender}.png"
    end
  end
end

app/views/achievements/index.html.erb
<% head_info :description, 'Основные достижения участников клуба Engirunners' %>
<div class="section my-5">
  <h1 class="fs-1 fw-bold mb-4"><%= head_info :title, 'Достижения' %></h1>
  <%= image_tag '/images/achievements.webp', class: 'img-fluid mt-4', alt: 'Достижения Engirunners', title: 'Достижения Engirunners' %>
  <% @achievements.each do |achievement| %>
    <% if achievement.title.present? %>
      <h2 class="mb-2"><%= achievement.title %></h2>
    <% end %>
    <div class="my-3 description">
      <%= sanitized_text achievement.description %>
    </div>
  <% end %>
</div>

app/views/athletes/_medals.html.erb
<%
  options = {
    1 => { color: '#ffad00', title: 'Первое место'},
    2 => { color: '#C0C0C0', title: 'Второе место'},
    3 => { color: '#CD7F32', title: 'Третье место'},
  }
%>
<% (1..3).each do |place| %>
  <% if count = @positions_count[place] %>
    <div class="mx-2" style="color: <%= options[place][:color] %>;">
      <span class="d-inline-block" data-tooltip-target="element" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="<%= options[place][:title] %>">
        <i class="medal-icon"></i>
      </span>
      x <%= count %>
    </div>
  <% end %>
<% end %>

app/views/athletes/index.html.erb
<% head_info :description, 'Список участников клуба Engirunners' %>
<div class="section my-5">
  <h1 class="fs-1 fw-bold"><%= head_info :title, 'Команда' %></h1>
  <%= image_tag '/images/command.webp', class: 'img-fluid mt-4', alt: 'Engirunners', title: 'Наша команда' %>
  <div class="m-0 row row-cols-1 row-cols-md-2 g-5">
    <% @athletes.each do |athlete| %>
      <div class="ps-0 pe-0 pe-md-5 col position-relative d-flex">
        <div class="flex-shrink-0">
          <%= image_tag athlete_image_path(athlete, variant: :thumb), class: 'athlete-thumb-img rounded-circle mt-1', title: athlete.name, alt: athlete.last_name, loading: 'lazy' %>
        </div>
        <div class="flex-grow-1 ms-3">
          <p class="fs-4 fw-medium mb-1 mb-md-2">
            <%= link_to athlete.name, athlete_path(athlete.nickname), class: 'stretched-link text-decoration-none text-body' %>
          </p>
          <p class="mb-1 mb-md-2">
            <% if @results_count.key? athlete.id %>
              выступлений за клуб:&nbsp;<%= @results_count[athlete.id] %>
            <% else %>
              Пока не было выступлений за клуб
            <% end %>
          </p>
          <% if athlete.debut_date %>
            <p class="text-muted mb-0">дата дебюта: <%= l athlete.debut_date %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/athletes/show.html.erb
<% head_info :description, "#{@athlete.name} - достижения и список результатов в команде Engirunners" %>
<div class="row mx-0 my-3">
  <div class="col-md-10 offset-md-1">
    <div class="text-center">
      <h1 class="fs-2 fw-bold my-3"><%= head_info :title, @athlete.name %></h1>
      <% unless @athlete.hide_birth_date %>
        <div class="mb-3 text-body-tertiary">
          Дата рождения: <%= @athlete.birth_date.strftime('%d.%m.%Y') %>
        </div>
      <% end %>
      <%= image_tag athlete_image_path(@athlete), class: 'athlete-img', alt: @athlete.last_name, title: @athlete.name %>
      <% if @positions_count.present? %>
        <div class="d-flex flex-row justify-content-center align-items-center" data-controller="tooltip">
          <%= render 'medals' %>
        </div>
      <% end %>
      <div class="d-flex flex-row flex-wrap justify-content-center align-items-center mt-4" data-controller="tooltip">
        <% %w[fiveverst s95 parkrun probeg strava telegram instagram lichess].each do |contact_type| %>
          <% next unless (contact_url = @athlete.public_send(:"#{contact_type}_link")).present? %>

          <%= link_to contact_url, class: 'text-decoration-none', target: '_blank', rel: 'noopener' do %>
            <%=
              image_tag(
                "/images/contacts/#{contact_type}.png",
                class: 'social-link',
                alt: t(contact_type),
                'data-tooltip-target' => 'element',
                'data-bs-toggle' => 'tooltip',
                'data-bs-placement' => 'top',
                'data-bs-title' => t(contact_type),
              )
            %>
          <% end %>
        <% end %>
      </div>
    </div>

    <% if @athlete.description.present? %>
      <div class="mt-4 row justify-content-center">
        <div class="col-10 col-md-6 col-xl-4 p-4 description">
          <%= sanitized_text @athlete.description %>
        </div>
      </div>
    <% end %>

    <h2 class="mt-5 fw-bold fs-3 text-center">Выступления за клуб</h2>
    <% total_count = @command_results.size %>
    <% if total_count.positive? %>
      <p class="text-body-tertiary text-center mt-3">Всего стартов: <%= total_count %></p>
      <table class="table table-striped mb-5">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Дата</th>
            <th scope="col">Эстафета</th>
            <th scope="col" class="hidden-on-phone">Формат</th>
            <th scope="col" class="text-center">Место</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          <% @command_results.each_with_index do |command_result, idx| %>
            <tr>
              <th scope="row"><%= total_count - idx %></th>
              <td><%= l command_result.event.date %></td>
              <td><%= link_to command_result.event.name, command_result.event %></td>
              <td class="hidden-on-phone"><%= command_result.form %></td>
              <td class="text-center"><%= command_result.position %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="my-5 text-center">Пока не было выступлений в эстафетах за клуб.</p>
    <% end %>
  </div>
</div>

app/views/athletes/show_ex.html.erb
<% head_info :title, @athlete.name %>
<% head_info :description, "#{@athlete.name} в настоящий момент в Engirunners не состоит" %>
<div class="text-center my-5" style="min-height: 25vh">
  <h1 class="fs-2 fw-bold mb-3 text-body-tertiary"><%= @athlete.name %></h1>

  <p><span class="fw-bold">Дата дебюта:</span> <%= l @athlete.debut_date, format: :long %> года</p>
  <p>
    <span class="fw-bold">Последний старт:</span>
    <%= l @athlete.results.joins(command: :event).order(date: :desc).pick(:date), format: :long %> года
  </p>
  <p>В настоящий момент в Engirunners не состоит</p>
</div>

app/views/events/index.html.erb
<% head_info :title, 'Список эстафет' %>
<% head_info :description, 'Эстафеты, в которых принимал участие клуб Engirunners с момента своего основания' %>
<div class="section my-5">
  <h1 class="fs-1 fw-bold">Эстафеты</h1>
  <%= image_tag '/images/events.webp', class: 'img-fluid my-3 my-md-4', alt: 'Эстафеты', title: 'Эстафеты' %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col no-pe">Дата</th>
        <th scope="col">Название</th>
        <th scope="col" class="text-center">Места</th>
        <th scope="col" class="text-center">Наших команд</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <% @events_grouped_by_year.each do |year, events| %>
        <tr class="table-light table-active">
          <th colspan="4" class="text-danger text-center fw-bold h3"><%= year %> год</th>
        </tr>
        <% events.each do |event| %>
          <tr>
            <th scope="row">
              <span class="d-none d-sm-block"><%= l event.date, format: :brief %></span>
              <span class="d-block d-sm-none"><%= l event.date, format: :short %></span>
            </th>
            <td><%= link_to event.name, event %></td>
            <td class="text-center"><%= event.commands.map(&:position).sort.join(', ') %></td>
            <td class="text-center"><%= event.commands.size %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/show.html.erb
<% head_info :description, "Результаты участия в эстафете #{@event.name}" %>
<div class="section my-5">
  <h1 class="fs-1 fw-bold mb-3"><%= head_info :title, @event.name %></h1>
  <%= image_tag @event.image.variant(:web), class: 'img-fluid mb-5', alt: @event.name, title: @event.name if @event.image.attached? %>
  <p>Дата проведения: <%= l @event.date, format: :long %> года</p>
  <p>Место: <%= @event.location %></p>

  <% @event.commands.order(:position, :position_abs).each do |command| %>
    <section class="fs-4 fw-semibold my-3 mt-md-4">Команда "<%= command.name %>"</section>
    <p>Формат: <%= command.form %></p>
    <p>Зачёт: <%= human_command_category command %></p>
    <p>Итоговое время: <%= human_result_time command %></p>
    <p>Место в категории: <%= command.position %>/<%= command.places_category %></p>
    <p>Место в абсолюте: <%= command.position_abs %>/<%= command.places_overall %></p>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Этап</th>
            <th scope="col">Имя</th>
            <th scope="col">Дистанция</th>
            <th scope="col">Время</th>
            <th scope="col" class="hidden-on-phone">Темп</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          <% command.results.order(:stage).includes(:athlete).each do |result| %>
            <tr>
              <th scope="row"><%= human_result_stage result %></th>
              <td><%= link_to result.athlete.name, athlete_path(result.athlete.nickname) %></td>
              <td><%= human_distance result.distance %></td>
              <td><%= human_result_time result %></td>
              <td class="hidden-on-phone"><%= human_result_pace result %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title><%= yield_head_info(:title, 'Беговой клуб') %> | Engirunners</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="<%= yield_head_info(:description, 'Беговой клуб Engirunners: о клубе, участниках, соревнованиях и их результатах') %>">
    <meta name="keywords" content="engirunners,клуб,бег,сообщество,результаты,соревнования,эстафеты,достижения,планы">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Беговой клуб Engirunners">
    <meta property="og:url" content="<%= root_url %>">
    <meta property="twitter:site" content="@engirunners">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:description" content="Cайт о беговом клубе Engirunners, его участниках, соревнованиях и их результатах">
    <meta name="twitter:title" content="Беговой клуб Engirunners">
    <meta name="twitter:image" content="<%= image_url '/images/main_header.png' %>">
    <meta property="og:image" content="<%= image_url '/images/main_header.png' %>">
    <meta property="og:image:width" content="300">
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg py-md-3 py-lg-4">
      <div class="container">
        <%= link_to root_path, class: 'navbar-brand text-uppercase fw-bold' do %>
          <%= image_tag '/logo_header.svg', class: 'img-logo', alt: 'logo', title: 'Engirunners' %>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключение меню">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item"><%= link_to 'Главная', root_path, class: "nav-link #{'active' if current_page? 'index'}" %></li>
            <li class="nav-item"><%= link_to 'О нас', about_path, class:"nav-link #{'active' if current_page? 'about'}" %></li>
            <li class="nav-item"><%= link_to 'Команда', athletes_path, class:"nav-link #{'active' if current_page? 'athletes'}" %></li>
            <li class="nav-item"><%= link_to 'Эстафеты', events_path, class:"nav-link #{'active' if current_page? 'events'}" %></li>
            <li class="nav-item"><%= link_to 'Достижения', achievements_path, class:"nav-link #{'active' if current_page? 'achievements'}" %></li>
            <li class="nav-item"><a href="/#partners" class="nav-link">Партнёры</a></li>
            <li class="nav-item"><a href="/#contacts" class="nav-link">Контакты</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Header -->
    <header class="main-header"></header>
    <!-- Content section-->
    <%= yield %>
    <!-- Footer-->
    <footer id="contacts" class="bg-dark py-5 mt-auto d-flex flex-column align-items-center justify-content-center footer-text">
      <%= image_tag '/logo_footer.svg', class: 'img-logo-footer my-3', alt: 'logo', title: 'Engirunners' %>
      <p class="mb-1">
        Напишите нам:
        <a href="mailto:engirunners@yandex.ru" class="footer-link" target="_blank" rel="noopener">engirunners@yandex.ru</a>
      </p>
      <p class="mb-1">
        Следите за нами в соцсетях:
        <a href="https://t.me/engirunners" class="footer-link" target="_blank" rel="noopener">@engirunners</a>
      </p>
      <div class="fs-1">
        <a href="https://t.me/engirunners" class="footer-link me-3" target="_blank" rel="noopener">
          <i class="fa-brands fa-telegram" role="img" aria-label="Telegram"></i>
        </a>
        <a href="https://vk.com/engirunners" class="footer-link me-3" target="_blank" rel="noopener">
          <i class="fa-brands fa-vk" role="img" aria-label="VK"></i>
        </a>
        <a href="https://www.instagram.com/engirunners/" class="footer-link" target="_blank" rel="noopener">
          <i class="fa-brands fa-instagram" role="img" aria-label="Instagram"></i>
        </a>
      </div>
    </footer>
  </body>
</html>

app/views/pages/index.html.erb
<section class="section mt-5 pb-4 pb-lg-5">
  <h1 class="fs-1 fw-bold">Беговой клуб быстрых технарей</h1>
  <%= image_tag '/images/main_relay.webp', class: 'img-fluid my-3 my-md-4', alt: 'Relay', title: 'Эстафета' %>
</section>
<!-- About us section -->
<section class="bg-secondary pt-4 pt-lg-5 pb-5">
  <div class="section">
    <div class="row position-relative">
      <div class="col-12 col-md-7 order-1 order-md-0">
        <%= image_tag '/images/main_group.webp', class: 'img-feed', alt: 'Engirunners', title: 'Наша команда' %>
      </div>
      <div class="col-12 col-md-5">
        <h2 class="fs-2 fw-bold mb-3 mt-md-2">
          <%= link_to 'О нас', about_path, class: 'stretched-link text-decoration-none text-body' %>
        </h2>
        <p>
          Суммарная статистика Engirunners
        </p>
      </div>
    </div>
  </div>
</section>
<!-- Main sections -->
<section class="mx-0 pt-4 pt-lg-5 pb-5">
  <div class="section">
    <div class="row mb-4 position-relative">
      <div class="col-12 col-md-5">
        <h2 class="fs-2 fw-bold mb-3 mt-md-2">
          <%= link_to 'Команда', athletes_path, class: 'stretched-link text-decoration-none text-body' %>
        </h2>
        <p>Актуальный состав Engirunners</p>
      </div>
      <div class="col-12 col-md-7 order-1 order-md-0 text-md-end">
        <%= image_tag '/images/command.webp', class: 'img-feed', alt: 'Engirunners', title: 'Наша команда' %>
      </div>
    </div>
    <div class="row mb-4 position-relative">
      <div class="col-12 col-md-5">
        <h2 class="fs-2 fw-bold mb-3 mt-md-2">
          <%= link_to 'Эстафеты', events_path, class: 'stretched-link text-decoration-none text-body' %>
        </h2>
        <p>То, что мы любим и делаем очень хорошо</p>
      </div>
      <div class="col-12 col-md-7 order-1 order-md-0 text-md-end">
        <%= image_tag '/images/events.webp', class: 'img-feed', alt: 'Эстафеты', title: 'Эстафеты' %>
      </div>
    </div>
    <div class="row position-relative">
      <div class="col-12 col-md-5">
        <h2 class="fs-2 fw-bold mb-3 mt-md-2">
          <%= link_to 'Достижения', achievements_path, class: 'stretched-link text-decoration-none text-body' %>
        </h2>
        <p>То, чем мы гордимся</p>
      </div>
      <div class="col-12 col-md-7 order-1 order-md-0 text-md-end">
        <%= image_tag '/images/achievements.webp', class: 'img-feed', alt: 'Достигая результатов', title: 'Достигая результатов' %>
      </div>
    </div>
  </div>
</section>
<!-- Partners section -->
<section id="partners" class="bg-light pt-4 pt-lg-5 pb-5">
  <div class="section">
    <h2 class="fs-2 fw-bold mb-3 mt-sm-2">Партнёры</h2>
    <p class="mb-2">Мы всегда готовы к сотрудничеству</p>
    <div class="d-flex flex-row flex-wrap justify-content-evenly align-items-center mx-2 my-4">
      <% Partner.includes(logo_attachment: :blob).find_each do |partner| %>
        <%= link_to partner.link, class: 'm-2', target: '_blank', rel: 'noopener' do %>
          <%= image_tag partner.logo.variant(:web), class: 'partner-img', alt: partner.name, title: partner.name %>
        <% end %>
      <% end %>
    </div>
  </div>
</section>